version: "3.8"

services:
  db:
    image: postgres:11.7
    container_name: postgres_test
    hostname: postgresql
    environment:
      - POSTGRES_USER=solfacil
      - POSTGRES_PASSWORD=solfacil
      - POSTGRES_DB=solfacil
    ports:
      - "5432:5432"
    networks:
      - poc_liquibase
    volumes:
      - postgres_test_data:/var/lib/postgresql/data/
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"

  jenkins:
    build:
      context: .
    image: solfacil/jenkins
    container_name: jenkins_test
    hostname: jenkins
    ports:
      - "8082:8080"
    networks:
      - poc_liquibase
    volumes: 
      - jenkins_test_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  poc_liquibase:
    name: poc_liquibase

volumes:
  postgres_test_data:
  jenkins_test_data:
